#ifndef AD_PROJECTION_2D_INTERFACE_H
#define AD_PROJECTION_2D_2D_INTERFACE_H
#include <vector>
#include <string>

#include "kernel_ad_projection_2d.h"
#include "kernel_ad_projection_2d_boundary_interface.hpp"

void AdProjection2dXDriver(const std::string BoundaryConditions,
			   const int nx,
			   const int ny,
			   const int nb_faces_x,
			   const int nb_faces_y,
			   const int nb_cells,
			   const int nb_nodes,
			   const RealType dx,
			   const RealType dy,
			   const RealType dt,
			   const RealType halo_width,
			   const RealType* predicted_u,
			   const RealType* e_lag,
			   const RealType* u_lag,
			   const RealType* v_lag,
			   const RealType* in_cell_mass,
			   RealType* out_u,
			   RealType* out_v,
			   RealType* out_e,
			   RealType* out_cell_mass,
			   RealType* directional_lagrangian_volume,
			   RealType* directional_lagrangian_density,
			   RealType* volume_fluxes_x,
			   RealType* mass_flux_x,
			   RealType* energy_flux_x,
			   RealType* density_gradient,
			   RealType* energy_gradient,
			   RealType* gradient_u,
			   RealType* gradient_v,
			   //timing
			   std::vector<RealType>& time_compute_volume_fluxes_X,
			   std::vector<RealType>& time_gradient_X,
			   std::vector<RealType>& time_mass_reconstruct_o2_X,
			   std::vector<RealType>& time_project_mass_X,
			   std::vector<RealType>& time_reconstruct_energy_o2_X,
			   std::vector<RealType>& time_project_energy_X,
			   std::vector<RealType>& time_gradient_nodal_X,
			   std::vector<RealType>& time_project_nodal_velocity_X,
			   std::vector<RealType> time_periodic_boundary);

void AdProjection2dYDriver(const std::string BoundaryConditions,
			   const int nx,
			   const int ny,
			   const int nb_faces_x,
			   const int nb_faces_y,
			   const int nb_cells,
			   const int nb_nodes,
			   const RealType dx,
			   const RealType dy,
			   const RealType dt,
			   const RealType halo_width,
			   const RealType* predicted_v,
			   const RealType* e_lag,
			   const RealType* u_lag,
			   const RealType* v_lag,
			   const RealType* in_cell_mass,
			   RealType* out_u,
			   RealType* out_v,
			   RealType* out_e,
			   RealType* out_cell_mass,
			   RealType* directional_lagrangian_volume_y,
			   RealType* directional_lagrangian_density_y,
			   RealType* volume_fluxes_y,
			   RealType* mass_flux_y,
			   RealType* energy_flux_y,
			   RealType* density_gradient,
			   RealType* energy_gradient,
			   RealType* gradient_u,
			   RealType* gradient_v,
			   //timing
			   std::vector<RealType>& time_compute_volume_fluxes_Y,
			   std::vector<RealType>& time_gradient_Y,
			   std::vector<RealType>& time_mass_reconstruct_o2_Y,
			   std::vector<RealType>& time_project_mass_Y,
			   std::vector<RealType>& time_reconstruct_energy_o2_Y,
			   std::vector<RealType>& time_project_energy_Y,
			   std::vector<RealType>& time_gradient_nodal_Y,
			   std::vector<RealType>& time_project_nodal_velocity_Y,		     
			   std::vector<RealType> time_periodic_boundary);


#endif 
