#ifndef DIRECT_PROJECTION_CORNER_FLUXES_2D_INTERFACE_H
#define DIRECT_PROJECTION_CORNER_FLUXES_2D_INTERFACE_H
#include <vector>
#include <string>

#include "direct_projection_corner_fluxes_2d_monomat_driver.hpp"
#include "direct_projection_corner_fluxes_2d_multimat_mix_driver.hpp"

void DirectProjectionCornerFluxes2dDriver(//in
					  const std::string BoundaryConditions,
					  const std::string TypeOfModel,
					  const int nx,
					  const int ny,
					  const int nb_faces_x,
					  const int nb_faces_y,
					  const int nb_cells,
					  const int nb_nodes,
					  const RealType dx,
					  const RealType dy,
					  const RealType dt,
					  const RealType halo_width,
					  const RealType gamma,
					  const RealType gamma_1,
					  const RealType gamma_2,
					  const RealType pi,
					  const RealType pi_1,
					  const RealType pi_2,
					  const RealType* predicted_u,
					  const RealType* predicted_v,
					  const RealType* e_lag,
					  const RealType* e_1_lag,
					  const RealType* e_2_lag,
					  const RealType* u_lag,
					  const RealType* v_lag,
					  const RealType* in_rho_1,
					  const RealType* in_rho_2,
					  const RealType* in_cell_mass,
					  const RealType* in_cell_mass_1,
					  const RealType* in_cell_mass_2,
					  const RealType* in_pressure,
					  const RealType* in_p_1,
					  const RealType* in_p_2,
					  const RealType* in_c_1,
					  const RealType* in_c_2,
					  const RealType* in_cell_volumic_fraction,
					  const RealType* cell_volumes,
					  // out
					  RealType* out_u,
					  RealType* out_v,
					  RealType* out_e,
					  RealType* out_cell_mass,
					  RealType* out_cell_mass_1,
					  RealType* out_cell_mass_2,
					  RealType* out_e_1,
					  RealType* out_e_2,
					  RealType* out_rho,
					  RealType* out_rho_1,
					  RealType* out_rho_2,
					  RealType* out_c_1,
					  RealType* out_c_2,
					  RealType* out_cell_volumic_fraction,
					  RealType* directional_lagrangian_volume,
					  RealType* directional_lagrangian_volume_y,
					  RealType* directional_lagrangian_density,
					  RealType* directional_lagrangian_density_y,
					  RealType* directional_lagrangian_density_1,
					  RealType* directional_lagrangian_density_1_y,
					  RealType* directional_lagrangian_density_2,
					  RealType* directional_lagrangian_density_2_y,
					  RealType* volume_fluxes_x,
					  RealType* volume_fluxes_y,
					  RealType* volume_fluxes_corner,
					  RealType* volume_fluxes_1_x,
					  RealType* volume_fluxes_1_y,
					  RealType* volume_fluxes_1_corner,
					  RealType* volume_fluxes_2_x,
					  RealType* volume_fluxes_2_y,
					  RealType* volume_fluxes_2_corner,
					  RealType* mass_flux_x,
					  RealType* mass_flux_y,
					  RealType* mass_flux_1_x,
					  RealType* mass_flux_1_y,
					  RealType* mass_flux_2_x,
					  RealType* mass_flux_2_y,
					  RealType* mass_corner_fluxes,
					  RealType* mass_1_corner_fluxes,
					  RealType* mass_2_corner_fluxes,
					  index_t* sign_x_corner_fluxes,
					  index_t* sign_y_corner_fluxes,
					  RealType* energy_flux_x,
					  RealType* energy_flux_y,
					  RealType* energy_flux_corner,
					  RealType* energy_flux_1_x,
					  RealType* energy_flux_1_y,
					  RealType* energy_flux_1_corner,
					  RealType* energy_flux_2_x,
					  RealType* energy_flux_2_y,
					  RealType* energy_flux_2_corner,
					  RealType* concentration_flux_x,
					  RealType* concentration_flux_y,
					  RealType* concentration_flux_corner,
					  RealType* bool_check_fluxes_x,
					  RealType* bool_check_fluxes_y,
					  RealType* density_gradient,
					  RealType* density_gradient_y,
					  RealType* density_gradient_diag,
					  RealType* density_gradient_antidiag,
					  RealType* density_1_gradient,
					  RealType* density_1_gradient_y,
					  RealType* density_1_gradient_diag,
					  RealType* density_1_gradient_antidiag,
					  RealType* density_2_gradient,
					  RealType* density_2_gradient_y,
					  RealType* density_2_gradient_diag,
					  RealType* density_2_gradient_antidiag,
					  RealType* energy_gradient,
					  RealType* energy_gradient_y,
					  RealType* energy_gradient_diag,
					  RealType* energy_gradient_antidiag,
					  RealType* energy_1_gradient,
					  RealType* energy_1_gradient_y,
					  RealType* energy_1_gradient_diag,
					  RealType* energy_1_gradient_antidiag,
					  RealType* energy_2_gradient,
					  RealType* energy_2_gradient_y,
					  RealType* energy_2_gradient_diag,
					  RealType* energy_2_gradient_antidiag,
					  RealType* concentration_gradient,
					  RealType* concentration_gradient_y,
					  RealType* concentration_gradient_diag,
					  RealType* concentration_gradient_antidiag,
					  RealType* reconstructed_density_faces_x,
					  RealType* reconstructed_density_faces_y,
					  RealType* reconstructed_density_1_faces_x,
					  RealType* reconstructed_density_1_faces_y,
					  RealType* reconstructed_density_2_faces_x,
					  RealType* reconstructed_density_2_faces_y,
					  RealType* reconstructed_energy_faces_x,
					  RealType* reconstructed_energy_faces_y,
					  RealType* reconstructed_energy_1_faces_x,
					  RealType* reconstructed_energy_1_faces_y,
					  RealType* reconstructed_energy_2_faces_x,
					  RealType* reconstructed_energy_2_faces_y,
					  RealType* reconstructed_concentration_faces_x,
					  RealType* reconstructed_concentration_faces_y,
					  RealType* gradient_u,
					  RealType* gradient_u_y,
					  RealType* gradient_u_diag,
					  RealType* gradient_u_antidiag,
					  RealType* gradient_v,
					  RealType* gradient_v_y,
					  RealType* gradient_v_diag,
					  RealType* gradient_v_antidiag,
					  RealType* interface_normal_x,
					  RealType* interface_normal_y,
					  //timing
					  std::vector<RealType>& time_compute_volume_fluxes_X,
					  std::vector<RealType>& time_gradient_X,
					  std::vector<RealType>& time_mass_reconstruct_o2_X,
					  std::vector<RealType>& time_project_mass_X,
					  std::vector<RealType>& time_reconstruct_energy_o2_X,
					  std::vector<RealType>& time_project_energy_X,
					  std::vector<RealType>& time_gradient_nodal_X,
					  std::vector<RealType>& time_project_nodal_velocity_X,
					  std::vector<RealType>& time_compute_volume_fluxes_Y,
					  std::vector<RealType>& time_gradient_Y,
					  std::vector<RealType>& time_mass_reconstruct_o2_Y,
					  std::vector<RealType>& time_project_mass_Y,
					  std::vector<RealType>& time_reconstruct_energy_o2_Y,
					  std::vector<RealType>& time_project_energy_Y,
					  std::vector<RealType>& time_gradient_nodal_Y,
					  std::vector<RealType>& time_project_nodal_velocity_Y,
					  std::vector<RealType> time_periodic_boundary);


#endif
