#ifndef KERNEL_LAGRANGE_FLUXES_2D_H
#define KERNEL_LAGRANGE_FLUXES_2D_H

typedef int index_t;

#ifdef __cplusplus
extern "C" {
#endif

RealType TimeStepLFMix(int nx,
		       int ny,
		       const RealType dx,
		       const RealType dy,
		       const int nb_mat,
		       const RealType CFL,
		       RealType* gamma_mix,
		       RealType* pi_prime_mix,
		       RealType* speed_of_sound_mix,
		       const RealType* gamma_k,
		       const RealType* pi_prime_k,
		       RealType* density,
		       RealType* pressure,
		       RealType** in_c_k,
		       const RealType* in_velocity_x,
		       const RealType* in_velocity_y);

void ComputeGradientAlpha(index_t nx, 
			  index_t ny, 
			  index_t nb_mat, 
			  const RealType dx,
			  const RealType dy,
			  RealType** in_c_k,
			  RealType** alphak_gradx_left,
			  RealType** alphak_gradx_right,
			  RealType** alphak_grady_bot,
			  RealType** alphak_grady_top
			  );
  
void ComputeGradientPplusPiPrime(index_t nx, 
			  index_t ny, 
			  const RealType dx,
			  const RealType dy,
			  RealType*  pressure,
			  RealType*  pi_prime_mix, 	 
			  RealType*  p_plus_pi_prime,	 
			  RealType*  p_plus_pi_prime_gradx,
			  RealType*  p_plus_pi_prime_grady	 
			  );

void ComputeGradientP(index_t nx, 
			  index_t    ny, 
			  RealType   dx,
			  RealType   dy,
			  int        nb_mat,	 
		          RealType*  pi_prime_mix,
			  RealType*  pressure,
		          RealType**  in_c_k,
		          RealType*  gamma_k,
			  RealType*  pi_prime_k,
			  RealType**  alphak_gradx_left,
			  RealType**  alphak_gradx_right,
			  RealType**  alphak_grady_bot,
			  RealType**  alphak_grady_top,
			  RealType*  p_plus_pi_prime_gradx,
			  RealType*  p_plus_pi_prime_grady,
			  RealType*  rho_e,
			  RealType*  rho_e_gradx_left,
			  RealType*  rho_e_gradx_right,
			  RealType*  rho_e_grady_bot,
			  RealType*  rho_e_grady_top,
			  RealType*  p_gradx_left,
			  RealType*  p_gradx_right,
			  RealType*  p_grady_bot,
		          RealType*  p_grady_top);

void ComputeGradientRho(index_t nx, 
			  index_t    ny, 
			  RealType   dx,
			  RealType   dy,
			  int        nb_mat,
			  RealType** in_rho_k,
		          RealType**  in_c_k,
			  RealType**  alphak_gradx_left,
			  RealType**  alphak_gradx_right,
			  RealType**  alphak_grady_bot,
			  RealType**  alphak_grady_top,
			  RealType*  rho_gradx_left,
			  RealType*  rho_gradx_right,
			  RealType*  rho_grady_top,
			  RealType*  rho_grady_bot,
			  RealType**  rhok_gradx,
			  RealType**  rhok_grady
			);

void ComputeHLL(index_t nx, 
		index_t    ny, 
		RealType   dx,
		RealType   dy,
		RealType*  rho_gradx_left,
		RealType*  rho_gradx_right,
		RealType*  rho_grady_top,
		RealType*  rho_grady_bot,
		RealType*  in_rho,
		RealType*  pressure,
		RealType*  in_u_cell,
		RealType*  in_v_cell,
		RealType*  speed_of_sound_mix,
		RealType*  p_gradx_left,
		RealType*  p_gradx_right,
		RealType*  p_grady_bot,
		RealType*  p_grady_top,
		RealType*  u_gradx_left,
		RealType*  u_gradx_right,
		RealType*  v_grady_bot,
		RealType*  v_grady_top,
		RealType*  p_xet,
		RealType*  p_yet,
		RealType*  u_et,
		RealType*  v_et
		);
  
void ComputeHLLFluxesZX(index_t nx, 
			index_t    ny, 
			RealType   dx,
			RealType   dy,
			int        nb_mat,
			RealType*  in_rho,
			RealType*  rho_e,
			RealType*  beta,
			RealType*  u_et,
			RealType*  p_xet,
			RealType** in_rho_k,
			RealType** rhok_gradx,
			RealType** in_c_k,
			RealType** alphak_gradx_left,
			RealType*  rho_gradx_left,
			RealType*  rho_e_gradx_left,
			RealType*  u_gradx_left,
			RealType*  v_gradx_left,
			RealType*  in_u_cell,
			RealType*  in_v_cell,
			RealType*  u2,
			RealType*  v2,
			RealType*  u2_gradx,
			RealType*  v2_gradx,
			RealType** alphak_gradx_right,
			RealType*  rho_gradx_right,
			RealType*  rho_e_gradx_right,
			RealType*  u_gradx_right,
			RealType*  v_gradx_right,
			RealType*  beta_gradx,
			RealType** masse_fluxes_k_x,
			RealType** alpha_beta_fluxes_k_x,
			RealType* rho_U_fluxes_x,
			RealType* rho_V_fluxes_x,
			RealType* beta_fluxes_x,
			RealType* rho_total_energy_fluxes_x
			);

void ComputeHLLFluxesZY(index_t nx, 
			index_t    ny, 
			RealType   dx,
			RealType   dy,
			int        nb_mat,
			RealType*  in_rho,
			RealType*  rho_e,
			RealType*  beta,
			RealType*  v_et,
			RealType*  p_yet,
			RealType** in_rho_k,
			RealType** rhok_grady,
			RealType** in_c_k,
			RealType** alphak_grady_bot,
			RealType*  rho_grady_bot,
			RealType*  rho_e_grady_bot,
			RealType*  u_grady_bot,
			RealType*  v_grady_bot,
			RealType*  in_u_cell,
			RealType*  in_v_cell,
			RealType*  u2,
			RealType*  v2,
			RealType*  u2_grady,
			RealType*  v2_grady,
			RealType** alphak_grady_top,
			RealType*  rho_grady_top,
			RealType*  rho_e_grady_top,
			RealType*  u_grady_top,
			RealType*  v_grady_top,
			RealType*  beta_grady,
			RealType** masse_fluxes_k_y,
			RealType** alpha_beta_fluxes_k_y,
			RealType* rho_U_fluxes_y,
			RealType* rho_V_fluxes_y,
			RealType* beta_fluxes_y,
			RealType* rho_total_energy_fluxes_y
			);


void ComputeVariablesFromFluxes(index_t nx, 
			index_t    ny, 
			RealType   dx,
			RealType   dy,
			RealType   dt_local,
			int        nb_mat,
			RealType   epsilon,	
			RealType*  gamma_k,
			RealType*  pi_prime_k,
			RealType*  in_rho_total_energy,
			RealType*  in_rho_U,
			RealType*  in_rho_V,
			RealType*  in_beta,
			RealType** in_masse_k_tmp,
			RealType** in_alpha_beta_k_tmp,
			RealType** masse_fluxes_k_x,
			RealType** alpha_beta_fluxes_k_x,
			RealType*  rho_U_fluxes_x,
			RealType*  rho_V_fluxes_x,
			RealType*  beta_fluxes_x,
			RealType*  rho_total_energy_fluxes_x,
			RealType** masse_fluxes_k_y,
			RealType** alpha_beta_fluxes_k_y,
			RealType*  rho_U_fluxes_y,
			RealType*  rho_V_fluxes_y,
			RealType*  beta_fluxes_y,
			RealType*  rho_total_energy_fluxes_y,
			RealType*  in_rho,
			RealType*  out_beta,
			RealType** in_rho_k,
			RealType** in_c_k,
			RealType*  in_u_cell,
			RealType*  in_v_cell,
			RealType*  out_rho_total_energy,
			RealType*  out_rho_U,
			RealType*  out_rho_V,
			RealType** masse_k,
			RealType** alpha_beta_k,
			RealType** out_alpha_beta_k_tmp,
			RealType** out_masse_k_tmp,
			RealType*  in_total_energy,
			RealType*  rho_e,
			RealType*  pressure
				);


void ComputeGradientBeta(index_t nx, 
			 index_t ny, 
			 RealType dx,
			 RealType dy,
			 RealType*  beta, 	 
			 RealType*  beta_gradx,
			 RealType*  beta_grady	 
			 ); 



#ifdef __cplusplus
}
#endif


#endif // KERNEL_LAGRANGE_FLUXES_2D_H
