#ifndef LAGRANGE_FLUXES_2D_INTERFACE_H
#define LAGRANGE_FLUXES_2D_INTERFACE_H
#include <vector>
#include <string>

#include "kernel_lagrange_fluxes_2d.h"

void LagrangeFluxes2dDriver(//in
			      const std::string BoundaryConditions,
			      const std::string TypeOfModel,
			      const int nb_mat,
			      const int nx,
			      const int ny,
			      const int nb_faces_x,
			      const int nb_faces_y,
			      const int nb_cells,
			      const int nb_nodes,
			      const RealType dx,
			      const RealType dy,
			      const RealType dt,
			      const RealType halo_width,
			      RealType* gamma_mix,
			      RealType* pi_prime_mix,
			      RealType* speed_of_sound_mix,			      
			      const RealType* gamma_k,
			      const RealType* pi_prime_k,
			      const RealType* predicted_u,
			      const RealType* predicted_v,
			      const RealType* e_lag,
			      const RealType* e_1_lag,
			      const RealType* e_2_lag,
			      const RealType* u_lag,
			      const RealType* v_lag,
			      const RealType* in_rho_1,
			      const RealType* in_rho_2,
			      const RealType* in_cell_mass,
			      const RealType* in_cell_mass_1,
			      const RealType* in_cell_mass_2,
			      RealType** in_c_k,
			      const RealType* in_cell_volumic_fraction,
			      const RealType* cell_volumes,
			      // out
			      RealType* out_u,
			      RealType* out_v,
			      RealType* out_e,
			      RealType* out_cell_mass,
			      RealType* out_cell_mass_1,
			      RealType* out_cell_mass_2,
			      RealType* out_e_1,
			      RealType* out_e_2,
			      RealType* out_rho,
			      RealType* out_rho_1,
			      RealType* out_rho_2,
			      RealType** out_c_k,
			      RealType* out_cell_volumic_fraction,
			      RealType* volume_fluxes_x,
			      RealType* volume_fluxes_y,
			      RealType* volume_fluxes_1_x,
			      RealType* volume_fluxes_1_y,
			      RealType* volume_fluxes_2_x,
			      RealType* volume_fluxes_2_y,
			      RealType* mass_flux_x,
			      RealType* mass_flux_y,
			      RealType* mass_flux_1_x,
			      RealType* mass_flux_1_y,
			      RealType* mass_flux_2_x,
			      RealType* mass_flux_2_y,
			      RealType* energy_flux_x,
			      RealType* energy_flux_y,
			      RealType* energy_flux_1_x,
			      RealType* energy_flux_1_y,
			      RealType* energy_flux_2_x,
			      RealType* energy_flux_2_y,
			      RealType* concentration_flux_x,
			      RealType* concentration_flux_y,
			      RealType* bool_check_fluxes_x,
			      RealType* bool_check_fluxes_y,
			      RealType* density_gradient,
			      RealType* density_gradient_y,
			      RealType* density_1_gradient,
			      RealType* density_1_gradient_y,
			      RealType* density_2_gradient,
			      RealType* density_2_gradient_y,
			      RealType* energy_gradient,
			      RealType* energy_gradient_y,
			      RealType* energy_1_gradient,
			      RealType* energy_1_gradient_y,
			      RealType* energy_2_gradient,
			      RealType* energy_2_gradient_y,
			      RealType* concentration_gradient,
			      RealType* concentration_gradient_y,
			      RealType* gradient_u,
			      RealType* gradient_u_y,
			      RealType* gradient_v,
			      RealType* gradient_v_y,
			      RealType* interface_normal_x,
			      RealType* interface_normal_y,
			      RealType** alphak_gradx_left,
			      RealType** alphak_gradx_right,
			      RealType** alphak_grady_bot,
			      RealType** alphak_grady_top);


#endif
