#ifndef LAGRANGE_FLUXES_2D_INTERFACE_H
#define LAGRANGE_FLUXES_2D_INTERFACE_H
#include <vector>
#include <string>

#include "kernel_lagrange_fluxes_2d.h"

void LagrangeFluxes2dDriver(//in
			      const std::string BoundaryConditions,
			      const std::string TypeOfModel,
			      const int nb_mat,
			      const int nx,
			      const int ny,
			      const int nb_cells,
			      const RealType dx,
			      const RealType dy,
			      const RealType dt,
			      const RealType halo_width,
			      RealType* gamma_mix,
			      RealType* speed_of_sound_mix,			      
			      RealType* gamma_k,
			      RealType* pi_prime_k,
			      RealType**  in_c_k,
			      RealType**         in_rho_k,
			      RealType*          in_rho,
			      const RealType*  in_cell_volumic_fraction,
			      const RealType*  cell_volumes,
			      // out
			      RealType* in_u_cell,
			      RealType* in_v_cell,
			      RealType*  out_u,
			      RealType*  out_v,
			      RealType*  out_e,
			      RealType*  out_e_1,
			      RealType*  out_e_2,
			      RealType*  out_rho,
			      RealType*  out_rho_1,
			      RealType*  out_rho_2,
			      RealType** out_c_k,
			      RealType*  out_cell_volumic_fraction,
			      RealType*  density_gradient,
			      RealType*  density_gradient_y,
			      RealType*  density_1_gradient,
			      RealType*  density_1_gradient_y,
			      RealType*  density_2_gradient,
			      RealType*  density_2_gradient_y,
			      RealType*  energy_gradient,
			      RealType*  energy_gradient_y,
			      RealType*  energy_1_gradient,
			      RealType*  energy_1_gradient_y,
			      RealType*  energy_2_gradient,
			      RealType*  energy_2_gradient_y,
			      RealType*  concentration_gradient,
			      RealType*  concentration_gradient_y,
			      RealType*  gradient_u,
			      RealType*  gradient_u_y,
			      RealType*  gradient_v,
			      RealType*  gradient_v_y,
			      RealType*  rho_total_energy,
			      RealType*  rho_e,
			      RealType*  rho_U,
			      RealType*  rho_V,
			      RealType*  pressure,
			      RealType*  beta,
			      RealType*  pi_prime_mix,
			      RealType*  p_plus_pi_prime,
			      RealType*  p_plus_pi_prime_gradx,
			      RealType*  p_plus_pi_prime_grady,	 
			      RealType* rho_e_gradx_left,
			      RealType* rho_e_gradx_right,
			      RealType* rho_e_grady_top,
			      RealType* rho_e_grady_bot,
			      RealType* p_gradx_left,
			      RealType* p_gradx_right,
			      RealType* p_grady_top,
			      RealType* p_grady_bot,
			      RealType* rho_gradx_left,
			      RealType* rho_gradx_right,
			      RealType* rho_grady_top,
			      RealType* rho_grady_bot,
			      RealType** alpha_beta_k,
			      RealType** alpha_beta_k_tmp,
			      RealType** masse_k,
			      RealType** masse_k_tmp,
			      RealType** alphak_gradx_left,
			      RealType** alphak_gradx_right,
			      RealType** alphak_grady_bot,
			      RealType** alphak_grady_top);


#endif
